<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 2 – PO33Q: Determinants of Democracy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-PO33Q.html" rel="next">
<link href="./01-PO33Q.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7c884608bb88d9d23eddf9360d6659a5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="theme-color" content="#1d1f2b" media="(prefers-color-scheme: dark)">
<meta name="theme-color" content="#1d1f2b" media="(prefers-color-scheme: light)">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-PO33Q.html"><span class="chapter-title">Week 2</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><img src="images/Crest_white.png" width="75" style="display:block; margin:auto; margin-bottom:3em;"> PO33Q: Determinants of Democracy – <br> Analysing Emergence, Survival, and Fall</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-PO33Q.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Week 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 9</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-PO33Q.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Markdown.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Markdown</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Downloads.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Downloads</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Full Glossary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-bib.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">List of References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#road-map-for-today" id="toc-road-map-for-today" class="nav-link active" data-scroll-target="#road-map-for-today">Road Map for Today</a>
  <ul class="collapse">
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  </ul></li>
  <li><a href="#principles-of-statistical-inference" id="toc-principles-of-statistical-inference" class="nav-link" data-scroll-target="#principles-of-statistical-inference">Principles of Statistical Inference</a>
  <ul class="collapse">
  <li><a href="#probability-distributions" id="toc-probability-distributions" class="nav-link" data-scroll-target="#probability-distributions">Probability Distributions</a>
  <ul class="collapse">
  <li><a href="#sampling-distributions" id="toc-sampling-distributions" class="nav-link" data-scroll-target="#sampling-distributions">Sampling Distributions</a></li>
  <li><a href="#the-t-distribution" id="toc-the-t-distribution" class="nav-link" data-scroll-target="#the-t-distribution">The t-Distribution</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  <li><a href="#tests-of-statistical-significance" id="toc-tests-of-statistical-significance" class="nav-link" data-scroll-target="#tests-of-statistical-significance">Tests of Statistical Significance</a></li>
  </ul></li>
  <li><a href="#linear-regression---theory" id="toc-linear-regression---theory" class="nav-link" data-scroll-target="#linear-regression---theory">Linear Regression - Theory</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a>
  <ul class="collapse">
  <li><a href="#population" id="toc-population" class="nav-link" data-scroll-target="#population">Population</a></li>
  <li><a href="#sample" id="toc-sample" class="nav-link" data-scroll-target="#sample">Sample</a></li>
  </ul></li>
  <li><a href="#ordinary-least-squares-ols" id="toc-ordinary-least-squares-ols" class="nav-link" data-scroll-target="#ordinary-least-squares-ols">Ordinary Least Squares (OLS)</a></li>
  </ul></li>
  <li><a href="#linear-regression-application" id="toc-linear-regression-application" class="nav-link" data-scroll-target="#linear-regression-application">Linear Regression – Application</a>
  <ul class="collapse">
  <li><a href="#the-basic-command" id="toc-the-basic-command" class="nav-link" data-scroll-target="#the-basic-command">The Basic Command</a></li>
  <li><a href="#interpreting-the-output" id="toc-interpreting-the-output" class="nav-link" data-scroll-target="#interpreting-the-output">Interpreting the Output</a>
  <ul class="collapse">
  <li><a href="#the-number-of-observations" id="toc-the-number-of-observations" class="nav-link" data-scroll-target="#the-number-of-observations">The Number of Observations</a></li>
  <li><a href="#the-all-important-p-value-in-regression" id="toc-the-all-important-p-value-in-regression" class="nav-link" data-scroll-target="#the-all-important-p-value-in-regression">The all-important p-value in Regression</a></li>
  <li><a href="#the-intercept" id="toc-the-intercept" class="nav-link" data-scroll-target="#the-intercept">The Intercept</a></li>
  <li><a href="#the-slope-coefficient" id="toc-the-slope-coefficient" class="nav-link" data-scroll-target="#the-slope-coefficient">The Slope Coefficient</a></li>
  <li><a href="#the-goodness-of-fit-r-squared" id="toc-the-goodness-of-fit-r-squared" class="nav-link" data-scroll-target="#the-goodness-of-fit-r-squared">The Goodness of Fit (R-Squared)</a></li>
  </ul></li>
  <li><a href="#choosing-variables" id="toc-choosing-variables" class="nav-link" data-scroll-target="#choosing-variables">Choosing Variables</a>
  <ul class="collapse">
  <li><a href="#can-i-choose-more-than-one-independent-variable" id="toc-can-i-choose-more-than-one-independent-variable" class="nav-link" data-scroll-target="#can-i-choose-more-than-one-independent-variable">Can I choose more than one independent variable?</a></li>
  <li><a href="#ceteris" id="toc-ceteris" class="nav-link" data-scroll-target="#ceteris">Ceteris Paribus</a></li>
  <li><a href="#parsimony" id="toc-parsimony" class="nav-link" data-scroll-target="#parsimony">Parsimony</a></li>
  <li><a href="#r-squared-again" id="toc-r-squared-again" class="nav-link" data-scroll-target="#r-squared-again">R-Squared Again</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#literature-recommendations" id="toc-literature-recommendations" class="nav-link" data-scroll-target="#literature-recommendations">Literature Recommendations</a></li>
  <li><a href="#important-disclaimer" id="toc-important-disclaimer" class="nav-link" data-scroll-target="#important-disclaimer">Important Disclaimer</a></li>
  </ul></li>
  <li><a href="#homework-for-week-3" id="toc-homework-for-week-3" class="nav-link" data-scroll-target="#homework-for-week-3">Homework for Week 3</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary">Glossary</a></li>
  <li><a href="#flashcards" id="toc-flashcards" class="nav-link" data-scroll-target="#flashcards">Flashcards</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Week 2</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="road-map-for-today" class="level1 unnumbered">
<h1 class="unnumbered">Road Map for Today</h1>
<div style="height:2em;">

</div>
<table style="border-collapse: collapse; width: 60%; margin-left: auto; margin-right: auto; table-layout: fixed;">
<tbody>
<!-- Lecture heading -->
<tr>
<td style="border-top: 3px double currentColor !important; border-bottom: none !important; font-weight: normal; padding: 8px;">
Lecture
</td>
</tr>
<!-- Indented subpoints until Break -->
<tr>
<td style="border: none !important; padding: 8px 8px 8px 24px;">
Causality
</td>
</tr>
<tr>
<td style="border: none !important; padding: 8px 8px 8px 24px;">
A Clear Theoretical Framework
</td>
</tr>
<tr>
<td style="border: none !important; padding: 8px 8px 8px 24px;">
Modernisation Theory
</td>
</tr>
<tr>
<td style="border: none !important; padding: 8px 8px 8px 24px;">
Critique &amp; Competing Approaches
</td>
</tr>
<!-- Break -->
<tr>
<td style="border-top: 1px dashed currentColor !important; border-bottom: 1px dashed currentColor !important; padding: 8px;">
Break
</td>
</tr>
<!-- Worksheet -->
<tr>
<td style="border: none !important; border-bottom: 3px double currentColor !important; padding: 8px;">
Linear Regression - Theory &amp; Application
</td>
</tr>
</tbody>
</table>
<div style="height:2em;">

</div>
<section id="learning-outcomes" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h2>
<p>After this week, students should be able to:</p>
<ul>
<li>Explain the role of theories in empirical political science research</li>
<li>Describe and critique the propositions of modernisation theory</li>
<li>Discuss the principles of statistical inference</li>
<li>Understand and apply linear regression (Ordinary Least Squares)</li>
<li>Appraise model fit in linear regression models</li>
</ul>
</section>
</section>
<section id="principles-of-statistical-inference" class="level1 unnumbered">
<h1 class="unnumbered">Principles of Statistical Inference</h1>
<p>Starting to write this, I am tackling the interesting task of condensing four weeks’ worth of material of my introductory quantitative module into a few paragraphs. But a brief overview of statistical inference and significance tests is essential for you to understand the interpretation of the methods we are going to explore. So let’s start with probability distributions.</p>
<section id="probability-distributions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="probability-distributions">Probability Distributions</h2>
<p>The term <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">probability distribution</a></span> sounds fancy, but really only implies that we are assessing the relative frequency with which a particular value occurs. So, for example, if I have six History students on the module, and four PAIS students, then the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/glossary-1.html">probability</a></span> of being a PAIS student is 40%. For categorical data, such as this, we can assign a probability to each category. But for continuous variables, such as the Polity V score, or per capita GDP this no longer works. Instead, we assign probabilities to an interval of numbers. In the following graph, I am putting the values of such a continuous variable on the x-axis, and then draw a curve over this which indicates the probability distribution for these values.</p>
<div id="fig-probability" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-probability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/prob1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-probability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Probability Distribution for a Continuous Variable
</figcaption>
</figure>
</div>
<p>In this graph, the values on the x-axis between alpha and beta have a probability of occurring that is equal to the orange area under the curve. This curve is bell-shaped, and symmetrical around the mean of the variable x, and is known as the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">normal distribution</a></span>. The beauty of this distribution is that the amount of probability that is contained in an interval around the mean depends solely on the number of standard deviations, denoted as <span class="math inline">\(\sigma\)</span>, of the variable x. So, for example, if I travel one standard deviation to the left and to the right from the mean, I will always have 68% of the area under the distribution in this interval.</p>
<div id="fig-righttail" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-righttail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/prob2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-righttail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Probability within one Standard Deviation
</figcaption>
</figure>
</div>
<p>For two standard deviations, this is equivalent to 96% and for three standard deviations 99.9%. Schematically this looks as follows:</p>
<div id="fig-normal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/prob3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Probabilities under the Normal Distribution
</figcaption>
</figure>
</div>
<p>The total area under the probability distribution is equal to 100%. So, if the orange area in <a href="#fig-righttail" class="quarto-xref">Figure&nbsp;<span>2</span></a> is equal to 68%, then the remaining area must be 32%. As this area is split equally into a left and a right side, the area on the right must be 16%. This is what is known as a right-tail probability. Here it is the probability beyond 1 standard deviation, or <span class="math inline">\(1 \sigma\)</span>.</p>
<p>This means that if we know how many standard deviations away from the mean of the distribution a value falls, we can make a statement on how likely it would be to observe a value that is higher than this value. For example, if I know the distribution of marks on a module, this would allow me to state how likely it was to achieve a First, or a mark of higher than 70. Assume that the average of an assessment was 63, and the standard deviation 9. Then the difference between the mean and the value we are interested in is equal to 70-63=7. To express this distance in units of standard deviations, we now divide 7 by 9, and obtain something that is called a z-score:</p>
<p><span class="math display">\[\begin{equation}
z=\frac{\text{Observation} - \text{Mean}}{\text{Standard Deviation}}
\end{equation}\]</span></p>
<p>In our case, z would be equal to 7/9, or 0.7777778. You can look this value up in a <a href="files/Downloads/Statistical Tables.pdf">z-table</a> which lists the right-tail probability for all conceivable values of z. For z=0.78 it returns a probability of 21.77%. With a mean of 63 and standard deviation of 9,the probability of scoring a First would be 21.77%.</p>
<p>This all works fine, so long as we are dealing with the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">population</a></span>. Sadly, we rarely have access to the population in the social sciences, however. Surveys, for example, are usually conducted for a small representative sub-group of the population, a <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">sample</a></span>. So, how do we make statements about the population if we only have access to a sample? The answer is: with a sampling distribution.</p>
<section id="sampling-distributions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sampling-distributions">Sampling Distributions</h3>
<p>Whenever we draw a sample from a population, the values we draw will vary. Therefore, also the mean of these values will vary each time. Imagine I draw a sample of 5 students from a seminar group, time and time again, and each time I calculate the average age of these 5 students. Sometimes the average will be high, sometimes it will be low, but – and here comes the magic – the value that will come up most often in these samples is the true mean of the population (all students in the seminar). We call this population value a <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">parameter</a></span>.</p>
<p>If we arrange all of the sample means we have obtained from sampling again and again, these means will form a distribution in their own right, the sampling distribution. This has the true population mean (let’s denote this as <span class="math inline">\(\mu\)</span>) in its centre. In <a href="#fig-sampling" class="quarto-xref">Figure&nbsp;<span>4</span></a>, for example, I have simulated a population with a mean of zero, and have drawn 9000 samples from this population, each with 30 observations. As you can see, the distribution of means of each of these 9000 samples forms a normal distribution which has zero, the population mean, at its centre.</p>
<div id="fig-sampling" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="prob3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Sampling Distribution
</figcaption>
</figure>
</div>
<p>So, we know the mean of the sampling distribution, but what about its standard deviation? We could of course take samples repeatedly from the population and calculate it, but that is wasteful. Instead, we estimate it by dividing the standard deviation of the one sample we usually have by the square root of the sample size. The result is the so-called <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">standard error</a></span>, denoted as “se”, the standard deviation of the sampling distribution.</p>
<p><span class="math display">\[\begin{equation}
se=\frac{s}{\sqrt{n}}
\end{equation}\]</span></p>
<p>where s is the sample standard deviation and n is the sample size.</p>
<p>The sample standard deviation varies with each sample we draw, however, and this introduces uncertainty into our analysis. The normal distribution cannot deal with this uncertainty, and so we have to abandon it in favour of the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">t-distribution</a></span>.</p>
</section>
<section id="the-t-distribution" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-t-distribution">The t-Distribution</h3>
<p>The t-distribution is also bell-shaped and symmetrical, centered around a fixed mean of zero. But, crucially, its shape is not static, but depends on the number of <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">degrees of freedom</a></span>. Degrees of freedom are constraints on the estimation process that reflect the number of independent pieces of information available. In our case, the constraint arises from estimating the population standard deviation <span class="math inline">\(\sigma\)</span> using the sample standard deviation, <span class="math inline">\(s\)</span>. For a single sample, the degrees of freedom are defined as n-1, where n is the sample size. Depending on these degrees of freedom, the t-distribution becomes wider or narrower, expressing the uncertainty we are incurring from working with a sample of a particular size. You can see in <a href="#fig-t" class="quarto-xref">Figure&nbsp;<span>5</span></a> that with increasing sample size the t-distribution becomes narrower and narrower, until – for an infinite sample size – it is equivalent to the normal distribution again. The smaller the sample size, the wider the t-distribution becomes. This means that as the sample size decreases we need to travel more standard deviations away from the mean in order to obtain a certain probability. More on this below under “Confidence Intervals”.</p>
<div id="fig-t" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/tdis.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Comparison of t-Distributions
</figcaption>
</figure>
</div>
<p>Using the sampling distribution, we can create a range of values that we think the true population value (like the average) falls into. This range is called a <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">confidence interval</a></span>. For example, a 95% confidence interval means that if we took many random samples and made a new interval each time, about 95% of those intervals would contain the true value.</p>
</section>
</section>
<section id="confidence-intervals" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p>How do we construct confidence intervals? We start by setting the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">confidence level</a></span> — the proportion of confidence intervals, constructed from repeated random samples of the same population using the same method, that are expected to contain the true population parameter. It is denoted by (1 - ), where () is the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">significance level</a></span>. For example, a 95% confidence level implies that 95% of such intervals would contain the true parameter in the long run.</p>
<p>Because the interval is constructed from a sample, we use the sampling distribution of the sample mean. We place the sample mean at the center of this distribution and treat it as our point estimate of the unknown population mean. To establish an interval around this estimate corresponding to the desired confidence level, we determine how many standard errors we must move to the left and right. Whereas under the normal distribution this was the z-score, under the t-score this number is called the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">t-score</a></span>, which can be found using a <a href="files/Downloads/Statistical Tables.pdf">statistical table</a>.</p>
<p>The appropriate t-score depends on the sample size (or the degrees of freedom, to be more precise). As hinted above, for smaller samples the t-distribution is wider, so we need to travel further away from the mean to achieve the same level of confidence than we would with a larger sample and a narrower distribution. For example, to construct a 95% confidence interval, we would use a t-score of approximately 2.306 for a sample of 9, but only 2.045 for a sample of 30.</p>
<p>As an example, reconsider our fictitious assessment with an average of 63, and the standard deviation 9. I used this for a probability statement in a population earlier, but now assume this is based on a sample of 15 students from a much larger module. Within which boundaries do we believe the parameter to fall with 95% confidence?</p>
<p>As a first step, we calculate the standard error:</p>
<p><span class="math display">\[\begin{equation}
se=\frac{s}{\sqrt{n}}= \frac{9}{\sqrt{15}} = 2.32379
\end{equation}\]</span></p>
<p>As we have 15 observations, we have 14 degrees of freedom (n-1) which corresponds to a t-score of 2.145. We can thus state that with 95% confidence the parameter, <span class="math inline">\(\mu\)</span>, falls between 58.02 and 67.98.</p>
<p><span class="math display">\[\begin{align}
\bar{y} - t \cdot se \le \;\; &amp;\mu \; \le \bar{y} - t \cdot se \\\\
63- 2.145 \cdot 2.32379 \le \;\; &amp;\mu \; \le 63 + 2.145 \cdot 2.32379 \\\\
58.01547 \le \;\; &amp;\mu \; \le 67.98453
\end{align}\]</span></p>
<p>where <span class="math inline">\(\bar{y}\)</span> is the average in the sample<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>We will come back to confidence intervals in the context of regression analysis. Let us now look at significance tests.</p>
</section>
<section id="tests-of-statistical-significance" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="tests-of-statistical-significance">Tests of Statistical Significance</h2>
<p>As you know from the lecture last week, in the social sciences we generally test whether we can explain behaviour or some kind of phenomenon through a particular theory. In practical terms this means that we distill the theory into testable statements, called hypotheses. Take this hypothesis, for example: The average level of democracy in the Middle East is statistically different from that of Europe. In this statement, we are no longer interested in establishing an interval of numbers within which we believe the average level of democracy in the Middle East to fall, but we are comparing it with a particular value, or point: the level of democracy in Europe. This kind of assessment is called a <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">significance test</a></span>.</p>
<p>Every significance test has two hypotheses, an alternative, and a null-hypothesis. The alternative hypothesis is the one I already stated:</p>
&nbsp;
<center>
H<span class="math inline">\(_\text{A}\)</span>: The average level of democracy in the Middle East is statistically different from that of Europe.
</center>
<p>&nbsp; &nbsp;</p>
<p>The null-hypothesis always represents no effect. In our case the region would have no impact on the democracy level, and the Polity V score of Europe and the Middle East would be identical.</p>
&nbsp;
<center>
H<span class="math inline">\(_0\)</span>: The average level of democracy in the Middle East is the same as in Europe.
</center>
<p>&nbsp; &nbsp;</p>
<p>The average Polity V score in the Middle East was -2.8 in 2015 with a standard deviation of 7.07 across 15 countries. The average Polity V score for Europe in the same year was 8.7.</p>
<div class="baser">
<details>
<summary>
How to obtain these values
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>me <span class="ot">&lt;-</span> <span class="fu">filter</span>(world, countrycode<span class="sc">==</span><span class="st">"BHR"</span> <span class="sc">|</span> <span class="co">#Bahrain</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"CYP"</span> <span class="sc">|</span> <span class="co">#Cyprus</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"EGY"</span> <span class="sc">|</span> <span class="co">#Egypt</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"IRN"</span> <span class="sc">|</span> <span class="co">#Iran</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"IRQ"</span> <span class="sc">|</span> <span class="co">#Iraq</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"ISR"</span> <span class="sc">|</span> <span class="co">#Israel</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"JOR"</span> <span class="sc">|</span> <span class="co">#Jordan</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"KWT"</span> <span class="sc">|</span> <span class="co">#Kuwait</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"LBN"</span> <span class="sc">|</span> <span class="co">#Lebanon</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"OMN"</span> <span class="sc">|</span> <span class="co">#Oman</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"QAT"</span> <span class="sc">|</span> <span class="co">#Qatar</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"SAU"</span> <span class="sc">|</span> <span class="co">#Saudi Arabia</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"ARE"</span> <span class="sc">|</span> <span class="co">#UAE</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                    countrycode<span class="sc">==</span><span class="st">"YEM"</span>   <span class="co">#Yemen</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>me_15 <span class="ot">&lt;-</span> <span class="fu">filter</span>(me, year<span class="sc">==</span><span class="dv">2015</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(me_15<span class="sc">$</span>polity5)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(me_15<span class="sc">$</span>polity5)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>world<span class="sc">$</span>un_region_name</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>europe <span class="ot">&lt;-</span> <span class="fu">filter</span>(world, un_region_name<span class="sc">==</span><span class="st">"Southern Europe"</span><span class="sc">|</span>  </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>                   un_region_name<span class="sc">==</span><span class="st">"Western Europe"</span> <span class="sc">|</span> </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>                   un_region_name<span class="sc">==</span><span class="st">"Eastern Europe"</span> <span class="sc">|</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                   un_region_name<span class="sc">==</span><span class="st">"Northern Europe"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>europe_15 <span class="ot">&lt;-</span> <span class="fu">filter</span>(europe, year<span class="sc">==</span><span class="dv">2015</span>)          </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(europe_15<span class="sc">$</span>polity5, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(me_15<span class="sc">$</span>gdppc, <span class="at">mu=</span><span class="fl">8.7</span>,  </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">data=</span>me_15)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</details>
</div>
<p>In order to ascertain whether the observed value of -2.8 is statistically different from the null-hypothesis value, 8.7, we need to make a probability statement. To be precise, we need to quantify the probability of observing a value that is more extreme than than one we have already observed if the null hypothesis was true. If this probability is small, then the value we have can be regarded as highly unusual and we can conclude that it is statistically different from the null-hypothesis value. This probability of observing a value more extreme than the one we have observed, assuming the null hypothesis is true, is the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">p-value</a></span>.</p>
<p>Usually, we want the p-value to be quite small, either 5% or 1%. R will obtain this for us, but so you know what happens behind the scenes, here is a quick summary. We place the null hypothesis into the centre of a sampling distribution, effectively pretending that this is our population parameter. In other words, we assume that the null hypothesis is true. Now we look at where in relation to this null hypothesis value our observed value falls. We are then able to calculate the distance between the observed value and the null-hypothesis value in units of standard error. This is equivalent to the t-value, our <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">test statistic</a></span>. We calculate it as follows:</p>
<p><span class="math display">\[\begin{equation}
t = \frac{\bar{y} - \mu_{0}}{se}, \quad \text{where} \, se = \frac{s}{\sqrt{n}}
\end{equation}\]</span></p>
<p>In our example:</p>
<p><span class="math display">\[\begin{equation}
t = \frac{-2.8 - 8.7}{1.826243} = -6.297081, \quad \text{where} \, se = \frac{7.07301}{\sqrt{15}}
\end{equation}\]</span></p>
<p>This places us quite far out into the tails of the t-distribution (see <a href="#fig-p" class="quarto-xref">Figure&nbsp;<span>6</span></a>), and as such the probability of observing a value more extreme is very small. Hence, we can regard our observed value of -2.8 as unusual and conclude the the average democracy level in the Middle East is statistically different from that of Europe. The precise p-value for this is 0.001283, well below our desired significance level of 5%.</p>
<div id="fig-p" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/sigtest.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: The p-Value
</figcaption>
</figure>
</div>
<p>I have displayed this here as a two-sided test. We did not specify whether we expect the level of democracy in the Middle East to be higher or lower than in Europe, just different. As both directions are therefore possible, the p-value is made up of the sum of the areas in the left and the right tails of the distribution. One-sided tests are possible, but generally in regression analysis the test is two-sided which is why I will leave it at that here.</p>
<div class="bulb">
<p><strong>Interpreting Significance Tests</strong></p>
<p>In these assessment, and when reporting statistical results more generally, you’ll be required to interpret the outcome of a significance test. To do this well, it’s important to use language that reflects what null hypothesis significance testing (NHST) actually tells us, without overstating what the test can conclude.</p>
<p>NHST works by starting with the null hypothesis - usually a claim like “there is no effect” or “there is no difference”. We use the data to test whether that assumption is plausible. If the p-value is small, it means that results as extreme as the one we observed — or more extreme — would be rare if the null hypothesis were true. So, we take that as evidence against the null. But if the p-value is large, then the data are consistent with the null. And that’s where your interpretation should stop (at least at the introductory level, to avoid stretching and overstating).</p>
<p>There are two possible outcomes of a significance test: (1) your p-value is <strong>below</strong> the required significance level, and (2) your p-value is <strong>above</strong> the required significance level. Let’s look at these in turn:</p>
<ol type="1">
<li><p>If your p-value is below the required significance level, you can say things like:</p>
<ul>
<li>“There is evidence of an effect.”</li>
<li>“We reject the null hypothesis.”</li>
<li>“The data provide evidence against the null hypothesis.”</li>
<li>“There is statistically significant evidence of a difference (or relationship, or effect).”</li>
</ul>
<p><span style="display:block; height: 0.5em;"></span></p>
<p>Avoid phrasing that implies certainty, such as:</p>
<ul>
<li>🚫 “We proved the alternative hypothesis.”</li>
<li>🚫 “We proved that there is an effect.”</li>
<li>🚫 “We accept the alternative hypothesis.”</li>
</ul></li>
</ol>
<p><span style="display:block; height: 0.1em;"></span></p>
<ol start="2" type="1">
<li><p>If your p-value is above the required significance level to reject the null hypothesis, you can say things like:</p>
<ul>
<li>“There is insufficient evidence for an effect (of a difference, for a relationship).”</li>
<li>“We cannot reject the null hypothesis.”</li>
<li>“We fail to reject the null hypothesis.”</li>
<li>“The results are consistent with the null hypothesis.”</li>
</ul>
<p><span style="display:block; height: 0.5em;"></span></p>
<p>Avoid phrasing that overstates what the test can tell you, such as:</p>
<ul>
<li>🚫 “We proved the null hypothesis.”</li>
<li>🚫 “We reject the alternative hypothesis.”</li>
<li>🚫 “The null hypothesis is true.”</li>
</ul></li>
</ol>
<p><span style="display:block; height: 0.1em;"></span></p>
<p>Having taught quantitative political analysis for many years, I know that students love to use the word “prove” when they interpret their results. But there is no proof in significance testing, because we deal with probability statements, not certainty.</p>
</div>
<p>And with that, we are finally ready to turn our attention to the actual topic for today: linear regression.</p>
</section>
</section>
<section id="linear-regression---theory" class="level1 unnumbered">
<h1 class="unnumbered">Linear Regression - Theory</h1>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p><span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">Regression</a></span> is the power house of the social sciences. It is widely applied and takes many different forms. In this section we are going to explore the linear variant, estimated through a method called Ordinary Least Squares (OLS). This type of regression is used if our dependent variable is continuous. In Week 3 we will have a look at regression with a binary dependent variable and the calculation of the probability to fall into either of those two categories. But let’s first turn to linear regression.</p>
</section>
<section id="what-is-it" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="what-is-it">What is it?</h2>
<div class="video">
<p><strong>Regression - What is it?</strong></p>
<p>YouTube link to follow</p>
</div>
<p>Regression is not only able to identify the direction of a relationship between an independent and a dependent variable, it is also able to quantify the size of the effect. Let us choose <code>y</code> as our dependent variable, and <code>x</code> as our independent variable. We have some data which we are displaying in a scatter plot:</p>
<div id="fig-scatter" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/scatter.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Scatter Plot
</figcaption>
</figure>
</div>
<p>With a little goodwill we can already see that there is a positive relationship: as <code>x</code> increases, <code>y</code> increases, as well. Now, imagine taking a ruler and trying to fit in a line that best describes the relationship depicted by these points. This will be our <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">regression line</a></span>.</p>
<p>The position of a line in a coordinate system is usually described by two items: the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">intercept</a></span> with the Y-axis, and the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">slope</a></span> of the line. The slope is defined as rise over run, and indicates by how much <span class="math inline">\(y\)</span> increases (or decreases is the slope is negative) if we add an additional unit of <span class="math inline">\(x\)</span>. In the notation which follows we will call the intercept <span class="math inline">\(\beta_{0}\)</span>, and the slope <span class="math inline">\(\beta_{1}\)</span>. It will be our task to estimate these values, also called <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">coefficients</a></span>. You can see this depicted graphically here:</p>
<div id="fig-regline" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/regline.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Regression Line
</figcaption>
</figure>
</div>
<p>In the context of the module, we would for example have per capita GDP on the x-axis (independent variable), and Polity V measuring the level of democracy on the y-axis (dependent variable). This would look like this in the year 2015:</p>
<div id="fig-modern" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-modern-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/case.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-modern-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Democracy and Development in 2015
</figcaption>
</figure>
</div>
<section id="population" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="population">Population</h3>
<p>We will first assume here that we are dealing with the population and not a sample. The regression line we have just drawn would then be called the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">Population Regression Function</a></span> (PRF) and is written as follows:</p>
<p><span class="math display">\[\begin{equation}
E(y|x_{i}) = \beta_{0} + \beta_{1} x_{i}
\end{equation}\]</span></p>
<p><span class="math inline">\(E(Y|X_{i})\)</span> reads as the expected value of <span class="math inline">\(y\)</span>, given a particular observation of <span class="math inline">\(x\)</span>, and so the population regression function is also known as the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">conditional expectation function</a></span>. It represents the average value of <span class="math inline">\(y\)</span> we expect to observe, if <span class="math inline">\(x\)</span> is equal to a particular value.</p>
<p>As you can see, the line is not intercepting with all observations – it only represents the conditional averages, after all. Only two observations are located on the line, and all others have a little distance between them and the PRF. These distances between <span class="math inline">\(E(y|x_{i})\)</span> and <span class="math inline">\(y_{i}\)</span> are called <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">error terms</a></span> and are denoted as <span class="math inline">\(\epsilon_{i}\)</span>.</p>
<div id="fig-errors" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/errors.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Errors
</figcaption>
</figure>
</div>
<p>To describe the observations <span class="math inline">\(y_{i}\)</span> we therefore need to add the error terms to the PRF:</p>
<p><span class="math display">\[\begin{equation}
y_{i} = \beta_{0} + \beta_{1} x_{i} + \epsilon_{i}
\end{equation}\]</span></p>
</section>
<section id="sample" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sample">Sample</h3>
<p>In reality we hardly ever have the population in the social sciences, and we generally have to contend ourselves with a sample. Nonetheless, we can construct a regression line on the basis of the sample, the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">Sample Regression Function</a></span> (SRF). It is important to note that the nature of the regression line we derive from the sample will be different for every sample, as each sample will have other values in it. Rarely, the PRF is the same as the SRF - but we are always using the SRF to estimate the PRF.</p>
<p>In order to flag this up in the notation we use to specify the SRF, we are using little hats over everything we estimate, like this:</p>
<p><span class="math display">\[\begin{equation}
\hat{y}_{i} = \hat{\beta}_{0} + \hat{\beta}_{1} x_{i}
\end{equation}\]</span></p>
<p>Analogously, we would would describe the observations <span class="math inline">\(y_{i}\)</span> by adding the estimated error terms <span class="math inline">\(\hat{\epsilon}_{i}\)</span> to the equation.</p>
<p><span class="math display">\[\begin{equation}
y_{i} = \hat{\beta}_{0} + \hat{\beta}_{1} x_{i} + \hat{\epsilon}_{i}
\end{equation}\]</span></p>
<p>These estimated error terms, <span class="math inline">\(\hat{\epsilon}_{i}\)</span>, are called <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">residuals</a></span>. The following graph visualises the relationship between an observation, the PRF, the SRF, the error terms, and the residuals.</p>
<div id="fig-srfprf" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-srfprf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/SRF_PRF.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-srfprf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Population vs.&nbsp;Sample Regression Function
</figcaption>
</figure>
</div>
</section>
</section>
<section id="ordinary-least-squares-ols" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ordinary-least-squares-ols">Ordinary Least Squares (OLS)</h2>
<p>When you eye-balled the scatter plot at the start of this Chapter in order to fit a line through it, you have sub-consciously done so by minimising the distance between each of the observations and the line. Or put differently, you have tried to minimise the error terms <span class="math inline">\(\hat{\epsilon}_{i}\)</span>. This is basically the intuition behind fitting the SRF mathematically, too. We try to minimise the sum of all error terms, so that all observations are as close to the regression line as possible. The only problem that we encounter when doing this is that these distances will always sum up to zero.</p>
<p>But similar to calculating the standard deviation where the differences between the observations and the mean would sum up to zero (essentially we are doing the same thing here), we simply square those distances. So we are not minimising the sum of distances between observations and the regression line, but the sum of the <strong>squared</strong> distances between the observations and the regression line. Graphically, we would end up with little squares made out of each <span class="math inline">\(\hat{\epsilon}_{i}\)</span> which gives the the method its name: <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">Ordinary Least Squares</a></span> (OLS).</p>
<div id="fig-ols" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/OLS.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Ordinary Least Squares
</figcaption>
</figure>
</div>
<div class="video">
<p><strong>Ordinary Least Squares (OLS)</strong></p>
<p>YouTube link to follow</p>
</div>
<p>We are now ready to apply this stuff to a PO33Q-related example!</p>
</section>
</section>
<section id="linear-regression-application" class="level1 unnumbered">
<h1 class="unnumbered">Linear Regression – Application</h1>
<section id="the-basic-command" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="the-basic-command">The Basic Command</h2>
<p>The command to run a regression in R is beguilingly simple:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(devar <span class="sc">~</span> indepvar, <span class="at">data=</span>dataframe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We specify an object into which we store the results of the regression, here <code>regression</code>, and assign a function to this object called <code>lm</code> which stands for “linear model”. It is then convention to state the dependent variable first in the command, which in our case will always be democracy. This is then followed by a tilde and the independent variable which you want to include.</p>
<p>In the case of modernisation theory, you might want to test what influence per capita GDP has on democracy. This week we are using the Polity V scale to measure democracy.</p>
<blockquote class="blockquote">
<p>The ‘Polity Score’ captures [the] regime authority spectrum on a 21-pont scale ranging from -10 (hereditary monarchy) to +10 (consolidated democracy). (…) The Polity scheme consists of six component measures that record key qualities of of executive recruitment, constraints on executive authority and political competition. It also records changes in the institutionalized qualities of governing authority.”<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</blockquote>
<p>We start by setting the working directory</p>
<p>and then load the <a href="files/Downloads/Europe.csv">Europe.csv</a> data set into the workspace. We subset this data frame to observations from the year 1994, only. Yes, I know it’s a long time ago, but I need an example that works for everything I want to show you this week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>europe <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Week 2/Europe.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>europe_1994 <span class="ot">&lt;-</span> <span class="fu">filter</span>(europe, year <span class="sc">==</span> <span class="st">"1994"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our dependent variable is called <code>polity5</code>. The independent variable is called <code>gpdpc</code>. We are now ready to run our first regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>reg_pol <span class="ot">&lt;-</span> <span class="fu">lm</span>(polity5 <span class="sc">~</span> gdppc, <span class="at">data=</span>europe_1994)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then produce a summary of the results as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = polity5 ~ gdppc, data = europe_1994)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.5657 -0.3115  0.6054  1.5330  3.3036 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.120e+00  7.785e-01   7.861 2.45e-08 ***
gdppc       1.377e-04  4.036e-05   3.411  0.00212 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.794 on 26 degrees of freedom
  (10 observations deleted due to missingness)
Multiple R-squared:  0.3092,    Adjusted R-squared:  0.2826 
F-statistic: 11.64 on 1 and 26 DF,  p-value: 0.002123</code></pre>
</div>
</div>
<p>We can extract the number of observations used for the estimation by calling:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(reg_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
</div>
<p>There is a lot of information in this, and I will take you through the output step by step now.</p>
</section>
<section id="interpreting-the-output" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="interpreting-the-output">Interpreting the Output</h2>
<section id="the-number-of-observations" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-number-of-observations">The Number of Observations</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(reg_pol)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
</div>
<p>Let’s deal with the last step first. The number of observations is equal to the number of countries in this case. We have subset the data to the year 1994, and so we have 28 countries in the analysis. This seems trivial for now, but it will become important later on. Once observations are missing, R drops them from the analysis – especially in developing countries where data are often missing in large quantities this can lead to a rapid decimation in the number of observations. This in turn is problematic for the strength inference we can draw from the analysis.</p>
</section>
<section id="the-all-important-p-value-in-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-all-important-p-value-in-regression">The all-important p-value in Regression</h3>
<div class="video">
<p><strong>The p-Value</strong></p>
<p>YouTube link to follow</p>
</div>
<p>It might seem odd to focus on the p-value before interpreting the coefficients substantively, but this is precisely what you have to do in practice, as well. If a regression coefficient is insignificant, then we have failed to reject the null hypothesis, and have no evidence for a relationship. This is it. This is all you can say. Should this happen to you in the assessment, please do not engage in speculation of “had the coefficient been significant, then it would suggest that…”. No.&nbsp;There is no relationship. State that, and move on. Only if there is a relationship you can move on to interpreting the coefficients substantively.</p>
<div class="warning">
<p>If you interpret insignificant coefficients substantively (other than that there is no relationship) in the assessment you will lose marks.</p>
</div>
<p>But how do you assess significance? We do a regression in order to ascertain whether there is a relationship between the independent and the dependent variable, or not. For testing whether there is one, we start from the assumption that there is none. This is what we call the null hypothesis; in our example here it would be that per capita GDP does not influence the level of democracy in a country.</p>
<p>Now, remind yourself of the normal distribution from the video which has the mean age in its centre. In the video we were interested whether age influences height. Assuming, that there is no relationship between age and height, a regression line would look as follows:</p>
<div id="fig-flatregr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flatregr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/height_line.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flatregr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Flat Regression Line
</figcaption>
</figure>
</div>
<p>The line is perfectly flat (the slope coefficient is zero), intercepting the y-axis at the mean. It does so, because the regression line is the value of y we would expect on average for a given x. If this value does not vary, it has to be the average of y. If we now put a zero slope coefficient, such as the one for height, just in the more general form of <span class="math inline">\(\beta_{2}\)</span> in the centre of a normal distribution, it looks like this:</p>
<div id="fig-betanull" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-betanull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/beta2_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-betanull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Null Hypothesis for <span class="math inline">\(\beta_{1}\)</span>
</figcaption>
</figure>
</div>
<p>What we want to test now, with regression, is whether the slope coefficient R has calculated for us (let me denote the estimated value of <span class="math inline">\(\beta_{1}\)</span> as <span class="math inline">\(\hat{\beta_{1}}\)</span>), is far enough from this mean of zero, to say that we can be sure to say that there <em>is</em> a relationship.</p>
<p>The statement that there <em>is</em> a relationship between the independent and the dependent variable, is called the alternative hypothesis. In our case the alternative hypothesis would read: “The level of per capita GDP influences the level of democracy in a country”.</p>
<p>So how far away from the centre of zero do we have to go to say that there is indeed relationship, or put differently, that we have enough evidence to reject the null hypothesis? The standard in political science is that we need to have a 5% probability of finding a value more extreme than the one we have observed. Under the curve in the following graph, that is equal to the orange area on the right. And that is the p-value.</p>
<div id="fig-pbeta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pbeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/beta2_highlight.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pbeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: p-value for <span class="math inline">\(\beta_{1}\)</span>
</figcaption>
</figure>
</div>
<p>If this area is 5% or less, then we have observed a value for the slope coefficient which is so far away from our assumed mean of zero, that we have sufficient evidence to reject the null hypothesis.</p>
<p>But now, you might say, a slope coefficient can also be negative – here we are only looking at the right hand-side, and therefore at the scenario in which a slope coefficient is positive. And you are right. The scatter plot could give us a negative line. So, if we want to move away far enough from the assumed mean of zero in the centre, we must do so in both directions, to the left and to the right. Now, we need a value that is so far out, that to either side of the distribution, 2.5% of the area are left under the curve (2.5% on the left plus 2.5% on the right make the overall 5% we are interested in). We call this a two-sided test, whereas the scenario above is a one-sided test. The p-values reported by R for the slope coefficients are always two-sided tests (unless we tell R not to, but we are not doing that on this module). This value gives us the area under the normal distribution to the left and the right beyond our observed value, as shown in this figure:</p>
<div id="fig-twobeta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-twobeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/beta2_twotail.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twobeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Two-Sided Test for <span class="math inline">\(\beta_{1}\)</span>
</figcaption>
</figure>
</div>
<p>The value we are looking at in R to determine the p-value, is in the column <span class="math inline">\(Pr(&gt;|t|)\)</span>.</p>
<div id="fig-pvalue" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/pvalue.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: p-value column
</figcaption>
</figure>
</div>
<p>In order to satisfy the requirement of the p-value being 5% or less, this value needs to be smaller than 0.05. Otherwise, more than 5% area are left, and we are not certain enough that our value is far enough away from the zero mean in the centre to say that it is “statistically different” from it. When we look at the value for the slope coefficient <code>gdppc</code> here, 0.00212, this means that the areas on the left and the right are jointly 0.21% – small enough for us to be sure to have found a value that is far enough away from zero to claim that there is a relationship. We therefore reject the null hypothesis: we find evidence for a relationship between per capita GDP and Polity V in Europe in the year 1994. Again, if we want to visualise this, the actual p-value of <span class="math inline">\(0.00212\)</span> would look like this:</p>
<div id="fig-empbeta" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-empbeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Week 2/beta2_critical_bounds.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-empbeta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Visualisation of p-value
</figcaption>
</figure>
</div>
</section>
<section id="the-intercept" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-intercept">The Intercept</h3>
<div id="fig-intercept" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-intercept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/intercept.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-intercept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Intercept output
</figcaption>
</figure>
</div>
<p>R always shows the value for the intercept in the intuitively labelled row “(Intercept)” and the column “Estimate”. In this case the value is 6.1. What does this coefficient mean, substantively? When you remember the graph depicting the regression line, this is the point where the line intercepts the y-axis. So, it is the value of <span class="math inline">\(y\)</span>, here democracy in the form of the Polity V score, when <span class="math inline">\(x\)</span>, here economic development in the form of GDP, is zero. So in other words, a country with a GDP per capita of zero would achieve a Polity V score of 6.1. The substantive interpretation sometimes makes sense (like here), but sometimes cannot be interpreted in this way.</p>
</section>
<section id="the-slope-coefficient" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-slope-coefficient">The Slope Coefficient</h3>
<div id="fig-slope" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-slope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/slope.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Slope output
</figcaption>
</figure>
</div>
<p>The slope coefficient is shown in the row depicting the name of the independent variable, here “gdp”, and again the column “Estimate”. Our slope here, is <span class="math inline">\(1.377e-04\)</span>. The <span class="math inline">\(e-4\)</span> means that we have to move the decimal point 4 units to the left, so written fully, this means <span class="math inline">\(0.0001377\)</span>. We interpret it as follows: for every additional unit of per capita GDP, measured in US$, the Polity V score increases by <span class="math inline">\(0.0001377\)</span>, on average. This seems very small, but when you consider the size of GDP per capita in many countries, it seems logical that this value is as small as it is. If the coefficient was negative, then this would mean that for for every additional unit of per capita GDP, measured in US$, the Polity V score would decrease by <span class="math inline">\(0.0001377\)</span>, on average.</p>
<div class="bulb">
<p><strong>Interpreting a coefficient</strong></p>
<p>The order in which to interpret a coefficient is as follows:</p>
<ol type="1">
<li>Is it significant? If not, all you can say is that there is no influence. There is insufficient evidence to support the alternative hypothesis.</li>
<li>If it is significant, you can interpret its size and direction according to the statistical model (for example, slope coefficent vs.&nbsp;partial slope coefficient).</li>
<li>What does the coefficient mean for the hypothesis? Look at the direction. Is the direction as predicted by the hypothesis? Then you have evidence to support the hypothesis. If the direction is inverse, then you have falsified the hypothesis, even though you have a significant coefficient.</li>
</ol>
</div>
</section>
<section id="the-goodness-of-fit-r-squared" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-goodness-of-fit-r-squared">The Goodness of Fit (R-Squared)</h3>
<div id="fig-rsquared" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rsquared-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/rsquared.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rsquared-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: R-squared output
</figcaption>
</figure>
</div>
<div class="video">
<p><strong>Goodness of Fit</strong></p>
<p>YouTube link to follow</p>
</div>
<p>As you have seen in the video, the goodness of fit is a measure to indicate how much of the variation in the dependent variable (democracy) the independent variable (per capita GDP) is explaining. For this, we take the ratio of the explained sum of squares over the total sum of squares. The resulting percentage is R<span class="math inline">\(^2\)</span>, also known as the <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">coefficient of determination</a></span>. This number can also be found on the R output, and is in our case <span class="math inline">\(0.3092\)</span>, or 30.92%. This value is not too bad for a single variable! The maximum we can explain is of course 100% with an R-Squared value of 1.0, even though this is a dream never achieved empirically. But we are still quite some distance of this dream, and can probably do better. There surely must be factors other than per capita GDP that explain democracy in Europe in the year 1994.</p>
</section>
</section>
<section id="choosing-variables" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="choosing-variables">Choosing Variables</h2>
<section id="can-i-choose-more-than-one-independent-variable" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="can-i-choose-more-than-one-independent-variable">Can I choose more than one independent variable?</h3>
<p>Yes, you can! And this is where the fun starts, because now we are getting a step closer to the real world. New modernisation posits that democracy is multi-causal, and does not rest on the influence of GDP alone. Instead, it puts forward a number of concepts that act as independent variables, one of which is health. We can measure health through Hospital beds (per 1,000 people), and include this in our model, on top of GDP. To do this we type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>reg_pol1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(polity5 <span class="sc">~</span> gdppc <span class="sc">+</span> enrol_gross, <span class="at">data=</span>europe_1994)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You see that adding independent variables is easy, we just add them on with a plus sign. It does not matter whether the expected direction of influence is positive or negative, always add additional variables with a “+”. The command ought to lead to the following output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg_pol1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = polity5 ~ gdppc + enrol_gross, data = europe_1994)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.6561 -0.3999  0.2543  1.2566  3.0044 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -8.327e+00  6.458e+00  -1.290  0.21061   
gdppc        1.129e-04  3.671e-05   3.076  0.00553 **
enrol_gross  1.476e-01  6.352e-02   2.323  0.02979 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.421 on 22 degrees of freedom
  (13 observations deleted due to missingness)
Multiple R-squared:  0.4184,    Adjusted R-squared:  0.3655 
F-statistic: 7.913 on 2 and 22 DF,  p-value: 0.002577</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nobs</span>(reg_pol1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
</div>
</section>
<section id="ceteris" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="ceteris">Ceteris Paribus</h3>
<p>Let us focus on the coefficient for gross primary school enrolment first. Its value is rounded <span class="math inline">\(1.476e-01\)</span>, or <span class="math inline">\(0.1476\)</span>, implying that for every additional percent of gross primary school enrolment, the Polity V score increases by <span class="math inline">\(0.1476\)</span> units on average. So far, so good, but as we have included other variables in the regression model, namely per capita GDP, we need to account for this fact in our interpretation. We do this by adding “all other things being equal” (Latin: <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">ceteris paribus</a></span>) to this interpretation. What does this mean? It means, that if we take into account the level of per capita GDP, and hold this level constant, then for every additional percent of gross primary school enrolment the Polity V score increases by <span class="math inline">\(0.1476\)</span> units on average. As such, we force the regression model to isolate the effect of gross primary school enrolment, by including other possible explanatory factors, such as per capita GDP. You will sometimes read this in articles in the form of “controlling for”. As the percentage of gross primary school enrolment only explains the Polity V score partially now, the coefficients in a multiple regression model are also known as <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">partial slope coefficients</a></span>.</p>
<p>To give you a different example: suppose we want to find out whether sex influences income. We could simply run a regression with income as the dependent variable, and sex as the independent variable. But we also know, that age influences income, as with increasing age people have more experience which is reflected in their salary. So even though we are not interested in the amount age influences income, we would include it in the regression model, so as to isolate the effect of the variable we are interested in: sex.</p>
<p>Back to our modernisation example and school enrolment. The p-value for this coefficient is <span class="math inline">\(0.02979\)</span>, and therefore well below the required 5% threshold. We can conclude that the percentage of gross primary school enrolment influences the level of democracy in Europe in the year 1994. Per capita GDP remains significant.</p>
</section>
<section id="parsimony" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="parsimony">Parsimony</h3>
<p>But can you just add independent variables at your leisure? The short answer is no. The long answer is: parsimony. This means “as few as possible, as many as necessary”. The “necessary” component is guided by the theoretical underpinning of your investigation. For example, you subscribe to new modernisation theory, and believe that that it is not only economic development in the form of per capita GDP that determines the level of democracy, but that indicators of social change also play an important role. Now it is your job as a researcher to decide how we measure social change. Do we include health? And if so, how do we measure it, say by number of hospital beds per person? Should we choose a different measure for education that measures educational outcomes more directly than enrolment? Then we might decide on literacy. But are these two enough to measure social change, or do we need to look at other facets? We seek to include as few as possible to produce an empirical picture of social change, but so many that we are doing proper justice to the theory.</p>
<p>We can then proceed to test different scenarios. For example, does economic development already explain democracy? What happens if we add social change? Or does social change explain democracy on its own, already? These questions lead to the topic of “model specification”, which we will discuss in greater detail in week 4.</p>
</section>
<section id="r-squared-again" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="r-squared-again">R-Squared Again</h3>
<p>As soon as we introduce more than one independent variable to the model, we cannot use “Multiple R-Squared” any more. The reason is that this measure cannot properly take into account added variables. It will either stay the same, or increase, it cannot decrease. This of course, makes no sense, for example if we add average shoe size in 1994 to the analysis, this would not help to explain democracy, but Multiple R-Squared would still likely go up. We therefore need a new measure, called <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">Adjusted R-Squared</a></span> which not only penalises us for adding more independent variables, but will also decrease if a variable takes explanatory power away from a model. You find it here:</p>
<div id="fig-ceteris" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ceteris-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="files/Week 2/ceteris.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ceteris-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22: Adjusted R-squared location
</figcaption>
</figure>
</div>
</section>
</section>
<section id="limitations" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="limitations">Limitations</h2>
<p>OLS is a great method to model the relationship between one or multiple independent variables on a dependent variable. But this only works for cross-sectional data. OLS cannot deal with <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">time-series data</a></span> a condition that is crucial when we want to model the emergence and survival of democracy.</p>
<p>Why? There is a bunch of assumptions that need to be satisfied in order for OLS to deliver us with accurate results, collectively known as the Classical Linear Assumptions (CLM). One of these is that the error terms (our <span class="math inline">\(\epsilon_i\)</span>s) are not correlated with one another. This assumption is rarely met in time series data, as for example the Polity V score does not miraculously begin to dependend on the percentage of gross primary enrolment in a given year. It will also depend to an extent on the percentage of gross primary enrolment in the previous year, and indeed on the Polity V score of the previous year. This would cause <span class="gls"><a href="https://drfloreiche.github.io/PO33Q/13-Glossary.html">autocorrelation</a></span> in the error terms which is bad news for the CLM.</p>
<p>As such, you will not be able to use linear regression in this format in the final assessment!</p>
</section>
<section id="literature-recommendations" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="literature-recommendations">Literature Recommendations</h2>
<ul>
<li><span class="citation" data-cites="fogarty:2023">Fogarty (2023)</span> — Chapter 11, read Chapter 12 if you want to be really good. <a href="https://warwick.summon.serialssolutions.com/#!/search/document?pn=1&amp;ho=t&amp;include.ft.matches=f&amp;fvf=ContentType,Newspaper%20Article,t%7CContentType,Book%20Review,t&amp;l=en-UK&amp;q=fogarty%20social%20science&amp;id=FETCHMERGED-warwick_catalog_b396978733">Online</a></li>
<li><span class="citation" data-cites="stinerock:2022">Stinerock (2022)</span> — Chapter 12 and Sections 13.1-13.5, 13.8 and 13.10. <a href="https://warwick.summon.serialssolutions.com/#!/search/document?pn=1&amp;ho=t&amp;include.ft.matches=f&amp;fvf=ContentType,Newspaper%20Article,t%7CContentType,Book%20Review,t&amp;l=en-UK&amp;q=stinerock%20r&amp;id=FETCHMERGED-warwick_catalog_b396975143">Online</a></li>
</ul>
</section>
<section id="important-disclaimer" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="important-disclaimer">Important Disclaimer</h2>
<p>I have discussed linear regression with you this week for two reasons:</p>
<ol type="1">
<li>I am trying to sketch the methodological development through which the relationship between economic development and democracy has been analysed over time. <span class="citation" data-cites="lipset:1959">Lipset (1959)</span> started with a simple correlation analysis, and this quickly developed into linear regression analysis, as it is more powerful and more sophisticated than correlation analysis.</li>
<li>It forms the foundation for the binary response models (probit in our case) which we will start with next week. To start with, we will only look at the probability to be democratic in a particular year across different countries. But in Week 7, we will extend this to not only investigate this relationship across countries, but also over time. This dynamic probit, or Markov Transition Model (MTM), is the model you need to apply in the assessment of the module. Please DO NOT stick to linear regression in the assessment, as OLS is not capable to deal with time-series data. The same applies for a cross-sectional probit. The only method permissible in the assessment is an MTM.</li>
</ol>
</section>
</section>
<section id="homework-for-week-3" class="level1 unnumbered">
<h1 class="unnumbered">Homework for Week 3</h1>
<p><strong>Students as Learners:</strong></p>
<ul>
<li>Finish this week’s worksheet</li>
<li>Read the <a href="https://rl.talis.com/3/warwick/lists/E5FA4027-27A7-AFB0-AAF4-C891BCCD83E2.html#2D4144BC-3D1D-6B65-FD54-248D4D342058">required literature for Week 3</a></li>
</ul>
<div style="height:1.5em;">

</div>
<p><strong>Students as Researchers:</strong></p>
<ul>
<li>Choose a geographical region, or adopt a global focus</li>
<li>Using literature, prepare a summary of the extent to which modernisation theory can explain democracy. Consult at least 3 different sources.</li>
</ul>
</section>
<section id="glossary" class="level1 unnumbered">
<h1 class="unnumbered">Glossary</h1>
<p>&nbsp;</p>
<div class="glossary-table">
<div class="cell" data-tbl-colwidths="[25,75]">
<div id="tbl-glossary2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[25,75]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-glossary2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">adjusted rsquared</td>
<td style="text-align: left;">The coefficient of determination for multiple regression.</td>
</tr>
<tr class="even">
<td style="text-align: left;">autocorrelation</td>
<td style="text-align: left;">The value of one error term does not allow us to predict the value of another error term. As such their covariances must be zero</td>
</tr>
<tr class="odd">
<td style="text-align: left;">causality</td>
<td style="text-align: left;">In order to establish a causal relationship, the following criteria must be met concurrently: 1. Relevance of the variables within the broader theoretical and empirical context of the research (a) Clear Theoretical Framework, (b) Clear conceptualization, (c) Exclusion of alternative explanations; 2. Asymmetry; 3. Significant (and sufficiently strong) statistical association</td>
</tr>
<tr class="even">
<td style="text-align: left;">ceteris paribus</td>
<td style="text-align: left;">All other things being equal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">coefficient</td>
<td style="text-align: left;">A coefficient is a numerical expression which is multiplied with the value of a variable</td>
</tr>
<tr class="even">
<td style="text-align: left;">coefficient of determination</td>
<td style="text-align: left;">Indicates the proportion of the variation in the dependent variable which is explained through the independent variable. It is defined as <span class="math inline">\(\frac{\text{Explained Sum of Squares}}{\text{Total Sum of Squares}}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">conditional expectation function</td>
<td style="text-align: left;">see Population Regression Function (PRF)</td>
</tr>
<tr class="even">
<td style="text-align: left;">confidence interval</td>
<td style="text-align: left;">A confidence interval is an estimated range, based on a sample, that is likely to contain the true population parameter (such as the mean). If the sampling process were repeated many times, approximately ( (1 - ) % ) of the resulting intervals would contain the true parameter. The value of ( ) determines the – for example, ( = 0.05 ) corresponds to a 95% confidence level, while ( = 0.01 ) corresponds to 99%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">confidence level</td>
<td style="text-align: left;">The confidence level is the proportion of confidence intervals, constructed from repeated random samples of the same population using the same method, that are expected to contain the true population parameter. It is denoted by ( 1 - ), where ( ) is the significance level. For example, a 95% confidence level implies that 95% of such intervals would contain the true parameter in the long run.</td>
</tr>
<tr class="even">
<td style="text-align: left;">degrees of freedom</td>
<td style="text-align: left;">Degrees of freedom express constraints on our estimation process by specifying how many values in the calculation are free to vary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">error term</td>
<td style="text-align: left;">The error term quantifies the distance between each observation and the corresponding point on the regression line. The terms are denoted as <span class="math inline">\(\epsilon_{i}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">intercept</td>
<td style="text-align: left;">The intercept is the point at which the regression line intersects the y-axis. In this book we denote it as <span class="math inline">\(\beta_{0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">normal distribution</td>
<td style="text-align: left;">The normal distribution is a bell-shaped probability distribution that is symmetrical around the mean. Approximately 68% of values fall within 1 standard deviation of the mean, 96% within 2 standard deviations, and 99.7% within 3 standard deviations. This is known as the empirical rule.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ordinary Least Squares</td>
<td style="text-align: left;">The method of fitting a regression line by means of minimizing the sum of the squared distances between the observations and the estimated values</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p-value</td>
<td style="text-align: left;">The p-value indicates the probability of obtaining a result equal to, or even more extreme than the observed value, assuming the null hypothesis is true. Common thresholds for significance are 0.05, 0.01, and 0.001. A smaller p-value suggests stronger evidence against the null hypothesis. The p-value is denoted as <span class="math inline">\(p\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;">parameter</td>
<td style="text-align: left;">A parameter is the value a statistic would assume in the long run. It is also called the Expected Value</td>
</tr>
<tr class="odd">
<td style="text-align: left;">partial slope coefficient</td>
<td style="text-align: left;">A partial slope coefficient measures the influence of a variable in multiple regression, holding all other independent variables in the model constant</td>
</tr>
<tr class="even">
<td style="text-align: left;">population</td>
<td style="text-align: left;">Collection of all cases which possess certain pre-defined characteristics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population Regression Function</td>
<td style="text-align: left;">The Population Regression Function (PRF) describes the expected distribution of <span class="math inline">\(y\)</span>, given the values of the independent variable(s) <span class="math inline">\(x\)</span>. It is also called the conditional expectation function (CEF) and can be denoted as <span class="math inline">\(E(y_{i} \mid x_{i})\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">probability</td>
<td style="text-align: left;">Refers to how many times out of a total number of cases a particular event occurs. We can also see it as the chance of a particular event occurring</td>
</tr>
<tr class="odd">
<td style="text-align: left;">probability distribution</td>
<td style="text-align: left;">Specifies the likelihood of all possible outcomes for a particular variable</td>
</tr>
<tr class="even">
<td style="text-align: left;">regression</td>
<td style="text-align: left;">Regression analysis determines the direction and magnitude of influence of one or more independent variables on a dependent variable</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regression line</td>
<td style="text-align: left;">The regression line describes how the dependent variable is functionally related to the values of the independent variable. It it defined by the intercept <span class="math inline">\(\beta_{0}\)</span> and the slope <span class="math inline">\(\beta_{1}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">residual</td>
<td style="text-align: left;">An estimation of the error term. The difference between an observation <span class="math inline">\(y_{i}\)</span> and the estimated value <span class="math inline">\(\hat{y}_{i}\)</span>. Denoted as <span class="math inline">\(\hat{\epsilon}_{i}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">sample</td>
<td style="text-align: left;">A sub-group of the population</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sample Regression Function</td>
<td style="text-align: left;">A regression line based on a randomly drawn sample</td>
</tr>
<tr class="odd">
<td style="text-align: left;">significance level</td>
<td style="text-align: left;">The significance level, denoted by <span class="math inline">\(\alpha\)</span>, is the threshold used in hypothesis testing to determine if a result is statistically significant. It represents the probability of rejecting the null hypothesis when it’s actually true (a Type I error). Common levels are 0.05 or 0.01, indicating 5% or 1% risk. We will cover this properly in Week 9.</td>
</tr>
<tr class="even">
<td style="text-align: left;">significance test</td>
<td style="text-align: left;">A significance test is a statistical method used to determine whether observed data provide enough evidence to reject a null hypothesis. It calculates a probability of observing data as extreme as, or more extreme than, the actual sample results, assuming the null hypothesis is true</td>
</tr>
<tr class="odd">
<td style="text-align: left;">slope</td>
<td style="text-align: left;">A slope is defined as rise over run, and so it tells us how many units of y we need to climb (or descend if the slope is negative) for every additional unit of the independent variable <span class="math inline">\(x\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">standard error</td>
<td style="text-align: left;">The standard deviation of the sampling distribution. It is defined as:<span class="math display">\[\begin{equation*}\sigma_{\bar{y}} = \frac{\sigma}{\sqrt{n}}\end{equation*}\]</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">t-distribution</td>
<td style="text-align: left;">The t-Distribution is bell-shaped and symmetrical around a mean of zero. Its shape is dependent on the degrees of freedom in the estimation process.</td>
</tr>
<tr class="even">
<td style="text-align: left;">test statistic</td>
<td style="text-align: left;">A test statistic is a value calculated from the sample data that is used to decide whether to reject the null hypothesis (H<span class="math inline">\(_0\)</span>) in a hypothesis test. It quantifies the degree to which the observed data diverges from what is expected under the null hypothesis. In a t-test, the test statistic is a t-value, which measures the distance between the sample mean and the (hypothesised) population mean, expressed in units of standard errors.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">time-series data</td>
<td style="text-align: left;">Time-series data review a certain characteristic over time <span class="math inline">\(t\)</span>, where <span class="math inline">\(t\)</span> runs from 1 to <span class="math inline">\(T\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">z-score</td>
<td style="text-align: left;">The z-score, sometimes also referred to as z-value, expresses in units of standard deviation how far an observation of interest falls away from the mean.</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-glossary2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Glossary Week 2
</figcaption>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
</section>
<section id="flashcards" class="level1 unnumbered">
<h1 class="unnumbered">Flashcards</h1>
<div class="flashcard">
<details>
<summary>
New Functions This Week
</summary>
<div style="padding-bottom:56.25%; position:relative; display:block; width: 100%">
<p><iframe width="100%" height="100%" src="files/flashcards/PO33Q_Week 2_New.html" frameborder="0" allowfullscreen="" style="position:absolute; top:0; left: 0"> </iframe></p>
</div>
<p>
&nbsp;
</p>
The data are available as a <a href="files/excelfiles/PO33Q_Week 2_New.csv">.csv file</a>.
</details>
</div>
<div class="flashcard">
<details>
<summary>
R Functions This Week
</summary>
<div style="padding-bottom:56.25%; position:relative; display:block; width: 100%">
<p><iframe width="100%" height="100%" src="files/flashcards/PO33Q_Week 2_All.html" frameborder="0" allowfullscreen="" style="position:absolute; top:0; left: 0"> </iframe></p>
</div>
<p>
&nbsp;
</p>
The data are available as a <a href="files/excelfiles/PO33Q_Week 2_All.csv">.csv file</a>.
</details>
</div>
<div class="flashcard">
<details>
<summary>
All R Functions So Far
</summary>
<div style="padding-bottom:56.25%; position:relative; display:block; width: 100%">
<p><iframe width="100%" height="100%" src="files/flashcards/PO33Q_Week 2_Consolidate.html" frameborder="0" allowfullscreen="" style="position:absolute; top:0; left: 0"> </iframe></p>
</div>
<p>
&nbsp;
</p>
The data are available as a <a href="files/excelfiles/PO33Q_Week 2_Consolidate.csv">.csv file</a>.
</details>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-fogarty:2023" class="csl-entry" role="listitem">
Fogarty, B. J. (2023). <em><span>Quantitative Social Science Data With R</span></em> (Second Edition). Thousand Oaks, <span>CA</span>: Sage.
</div>
<div id="ref-lipset:1959" class="csl-entry" role="listitem">
Lipset, S. M. (1959). <span class="nocase">Some Social Requisites of Democracy: Economic Development and Political Legitimacy</span>. <em>The American Political Science Review</em>, <em>53</em>(1), 69–105. <a href="https://doi.org/10.2307/1951731">https://doi.org/10.2307/1951731</a>
</div>
<div id="ref-stinerock:2022" class="csl-entry" role="listitem">
Stinerock, R. (2022). <em><span class="nocase">Statistics with R – A Beginner’s Guide</span></em> (Second Edition). Thousand Oaks, <span>CA</span>: Sage.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>For the pedants: I am aware this should read <span class="math inline">\(\bar{y} - t_{\alpha/2} \cdot se \le \mu \le \bar{y} - t_{\alpha/2} \cdot se\)</span>, but I have left the subscripts out to make it less confusing here.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For more detail see http://www.systemicpeace.org/polityproject.html.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script>
document.addEventListener("DOMContentLoaded", function() {
  const toc = document.querySelector("nav#TOC");
  if (toc) {
    const link = document.createElement("div");
    link.innerHTML = `
      <div style="margin-top:1em; font-family: Lexend, sans-serif; font-size:0.9em;">
        <a href="https://drfloreiche.github.io/" target="_blank" style="color:#cd6118; text-decoration:none;">
          Back to Flo's Home
        </a>
      </div>
    `;
    toc.appendChild(link);
  }
});
</script>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const buttons = document.querySelectorAll(".delayed-download");

    buttons.forEach(function (btn) {
      const releaseDate = new Date(btn.dataset.date);
      const now = new Date();

      if (now >= releaseDate) {
        btn.classList.remove("disabled");
        btn.setAttribute("aria-disabled", "false");
        btn.setAttribute("href", btn.dataset.path);
        btn.setAttribute("download", btn.dataset.path.split('/').pop());
        btn.innerHTML = btn.dataset.label || "📄 Download Document";
      }
    });
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-PO33Q.html" class="pagination-link" aria-label="Week 1">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Week 1</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-PO33Q.html" class="pagination-link" aria-label="Week 3">
        <span class="nav-page-text"><span class="chapter-title">Week 3</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>